source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TechTeamer/ios-xc-pdfium.git'

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared', :modular_headers => true
end