name: Build Desktop Distribution (Ubuntu Self-Hosted)

on:
  push:
    branches: [ desktop_publish ]
  pull_request:
    branches: [ desktop_publish ]
  workflow_dispatch:

jobs:
  build:
    name: Build on Self-Hosted Ubuntu
    runs-on: [self-hosted, linux]

    steps:
      - name: Create BuildConfig manually
        run: |
          mkdir -p shared/build/generated/source/buildConfig/commonMain/kotlin
          cat << 'EOF' > shared/build/generated/source/buildConfig/commonMain/kotlin/BuildConfig.kt
          package com.moly3.core_domain

          object BuildConfig {
              const val SyncServerUrl = "https://example.com"
              const val SyncServerToken = "TOKEN_VALUE"
              const val IsRelease = true
          }
          EOF
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JetBrains Runtime 21
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: gradle

      - name: Verify Java
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release Distribution
        run: ./gradlew :shared:packageReleaseDistributionForCurrentOS

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-linux
          path: shared/build/compose/binaries/**/*
#name: Build Desktop Distributions
#
#on:
#  push:
#    branches: [ desktop_publish ]
#  pull_request:
#    branches: [ desktop_publish ]
#  workflow_dispatch:
#
#jobs:
#  build:
#    name: Build on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      # Install JetBrains Runtime (JBR) 21
#      - name: Setup JetBrains Runtime 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'jetbrains'
#          java-version: '21'
#          cache: gradle
#
#      - name: Verify Java
#        run: java -version
#
#      # Make gradlew executable on Unix systems
#      - name: Grant execute permission for gradlew
#        if: runner.os != 'Windows'
#        run: chmod +x gradlew
#
#      - name: Build Release Distribution
#        run: ./gradlew :shared:packageReleaseDistributionForCurrentOS
#        shell: bash
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: desktop-${{ runner.os }}
#          path: shared/build/compose/binaries/**/*